apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster3

generators:
- siteconfig.yaml

resources:
- pull-secret.yaml
- bmc-secret.yaml
- role-binding.yaml
- job-monitor-cluster-install.yaml
- request_cm.yaml
# - job-monitor-cluster-upgrade.yaml
# - managedclusteraction.yaml
# - managedclusteraction-restore.yaml
# - managedclusterview.yaml