kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ztprole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ztp-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
