---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-oadp-operator
spec:
  channel: "stable-1.1" 
  installPlanApproval: "Automatic"
  name: redhat-oadp-operator
  source: "redhat-operators" 
  sourceNamespace: openshift-marketplace
