# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "example-sno"
  namespace: "example-sno"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.31-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaqy7YhU9yx28InBRttTWDrsAMqn1txv4Z7ObxrK5ywlILf8LZdWMf8AehwMcxYrkwfC5G48dej6lKXkopQwmu7HCvTtVeU8gn07J6kSl3riAGsbX1wbuCiCjxIXUtHDZUCqc/ZUF/b6efGW0xcmc3fg3xgSWz3YYsH4zWxv211ISfavOjHTHQuVr7ibzEGJrz5S4xJJAY8v9XaYkxbUcaMm2IUFQG7S3RRMywMCSvyhUlPM6/btIVKXfiPy3+nnXhtll2zM3OIVSLOwGQDYhwRxP9TX3vyxidekmxk2gor1aL8S364nNipZITXx5hMHRWrtAX+bgb3FHDdRn9BEYOPLvPVNPKfFZiNULp9ar9QrV1wcfWYGuJ9QSkwfDuRkWVD3KgoZpLEsujP6eAGacyh8jhcv/M5SY5L/sPiX8fklBNWLSuPpMhZAAM1LeKz8iV/GK3jDdVA7nhG7MTRAB0RHnRljDkGcfiEbB+9VmAf+NrfmorPYDL/24o8n1R7tk= mabe@utility.mabe.com"
  clusters:
  - clusterName: "example-sno"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: "v4.10"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "example-sno"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.86.0/24
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is creted for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno"
        role: "master"
        bmcAddress: "redfish-virtualmedia+http://192.168.86.30:8000/redfish/v1/Systems/9c90293c-9fcb-468d-812f-721256803e35"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "52:54:00:22:f0:07"
        bootMode: "UEFI"
        # rootDeviceHints:
        #   deviceName: "/dev/sda"

        #rootDeviceHints:
        #  hctl: '0:1:0'
        #cpuset: "0-1,52-53"
        # nodeNetwork:
        #   interfaces:
        #     - name: 
        #       macAddress: "02:04:00:00:00:66"
        #   config:
        #     interfaces:
        #       - name: ens192
        #         type: ethernet
        #         state: up
        #         macAddress: "02:04:00:00:00:66"
        #         ipv4:
        #           enabled: true
        #           address:
        #           - ip: 192.168.123.5
        #             prefix-length: 24
        #         ipv6:
        #           enabled: false
        #           #address:
        #           # For SNO sites with static IP addresses, the node-specific,
        #           # API and Ingress IPs should all be the same and configured on
        #           # the interface
        #           #- ip: 1111:2222:3333:4444::aaaa:1
        #           #  prefix-length: 64
        #     dns-resolver:
        #       config:
        #         search:
        #         - example.com
        #         server:
        #         - 192.168.123.1
        #     routes:
        #       config:
        #       - destination: 0.0.0.0/0
        #         next-hop-interface: ens192
        #         next-hop-address: 192.168.123.1
        #         table-id: 254
