apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/instance: clusters
  name: job-monitor-cluster-install
  namespace: sno1
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  template:
    spec:
      containers:
      - command:
          - /bin/bash
          - "-c"
          - "sleep 1000"
        name: monitor-cluster-install
        image: registry.redhat.io/openshift4/ose-cli
      restartPolicy: Never

